.github/workflows/build.yml

Add a `github workflow`: auto build `linux` `macos` `windows` version package for `dioxus-cli`

ci: release build workflow

---

src/assets/index.html

Fixes https://github.com/DioxusLabs/cli/issues/27

Call wasm main if debug start is missing

---

src/config.rs

https://github.com/DioxusLabs/cli/issues/20

Allow package configuration

---

src/config.rs

https://github.com/DioxusLabs/cli/issues/19

Take executable from configured bin

---

src/assets/index.html
src/builder.rs
src/config.rs

- add support for web.base_path in dioxus.toml to allow multi level routes
- set index on 404 to true (highly desired for SPA)

Better support for SPA

---

src/assets/index.html

Probably not the greatest concern given the context, but quirks mode is best avoided, and browsers give annoying messages about it in the console.

Opt into standards mode

---

src/builder.rs
src/cli/build/mod.rs
src/cli/cfg.rs
src/cli/serve/mod.rs
src/config.rs

Complete build flags

---

Cargo.toml

update hot_reload to hot-reload

---

src/cli/cfg.rs
src/cli/serve/mod.rs
src/server/mod.rs

feat: set `port` configurable

---

Cargo.lock
Cargo.toml
src/server/hot_reload.rs
src/server/mod.rs

feat: clean warning info

---

src/server/hot_reload.rs
src/server/mod.rs

fix single line rsx hot reloading

---

Dioxus.toml
docs/src/configure.md
src/builder.rs
src/config.rs
src/tools.rs

Added support for tailwind-css as a tool.
Adding  release profile handling for tailwind-css by minifying the bundle.
Added the option "-Oz" in release profile for wasm-opt.
Fixed typo in src/config.rs.
Updated docs in configure.md.
Updated Dioxus.toml by adding tailwind tool.

[TOOL] Adding tailwind-css

---

Cargo.lock
Cargo.toml
src/builder.rs
src/server/mod.rs
src/tools.rs

Fixes https://github.com/DioxusLabs/dioxus/issues/531
`notify` has a breaking change in 5.0.0-pre.16, this updates for that change.
CI also now passes, in case you want to re-enable that:
https://github.com/trevyn/dioxus-cli/runs/7837315479
https://github.com/DioxusLabs/cli/actions/workflows/main.yml

Fix `notify` and make CI pass

---

.github/workflows/build.yml

Added new target: 
**x86_64-unknown-linux-gnu**

update build.yml: add new target

---

src/cli/mod.rs

update: match comments to readme

---

Cargo.lock
Cargo.toml
src/cli/serve/mod.rs
src/hot_reload/mod.rs
src/server/hot_reload.rs
src/server/mod.rs

update hot reloading to work with templates

---

Cargo.lock
src/cli/serve/mod.rs

Crate out directory if it doesn't exist on serve

---

src/cli/create/mod.rs
src/cli/mod.rs

Two small typos, although that `sevre` one might look harmful.

chore: typos

---

src/server/mod.rs

get_ip hangs after reload runs in dioxus serve on Windows.
```
Dioxus @ v0.1.5 [22:56:43]
> Local : http://localhost:8080/
> NetWork : http://192.168.3.14:8080/
> Profile : Debug
> Hot Reload : Normal
> Index Template : Default
> URL Rewrite [index_on_404] : True
> Build Time Use : 1972 millis
[INFO] A perfect compilation!
...
Project Reloaded: Changed 1 files. [22:56:56]
> Local : http://localhost:8080/
```
UdpSocket::bind from Watcher seemed to hang, so get_ip is now called only once on startup.

fix: get_ip on watcher hangs on windows

---

Cargo.lock
Cargo.toml

Fixes compilation on master by changing from local dependencies to git dependencies
closes #102

use git dependencies

---

Cargo.lock
Cargo.toml
src/server/mod.rs

companion to https://github.com/DioxusLabs/dioxus/pull/839 (don't merge until that PR is merged) to log errors in the CLI when hot reloading fails instead of panicking

Log io errors instead of panicking for hot reloading

---

src/server/mod.rs

Fixes the cli ignoring non .rs files when hot reloading is enabled

Fix reloading non rust files when hot reloading is enabled

---

src/server/mod.rs

This was meant to be in the original PR #109 (see https://github.com/DioxusLabs/cli/pull/109#discussion_r1153444426).

Add proxy routes in startup_default(…)

---

src/cli/serve/mod.rs

#122 fixed `--features` for `dioxus build`, this PR adds the same for `dioxus serve`

propagate `features` to `dioxus serve`

---

src/builder.rs
src/cargo.rs
src/cli/cfg.rs
src/cli/plugin/mod.rs
src/cli/serve/mod.rs
src/cli/translate/mod.rs
src/config.rs
src/plugin/mod.rs
src/server/mod.rs
src/tools.rs

Make git clone repo err clear

---

src/server/mod.rs

"W" -> "w". In ASCII, that is +32 :) Is this the smallest PR ever?

Fix typo: "NetWork" -> "Network"

---

src/builder.rs

Fixes the issue in #154
It appears the compiler process is exiting immediately, and when the stream_stdout is dropped before the error is returned it stops the CLI.

Fix some errors not being reported

---

docs/src/cmd/README.md
docs/src/cmd/build.md
docs/src/cmd/clean.md
docs/src/cmd/serve.md
docs/src/cmd/translate.md
docs/src/configure.md
docs/src/creating.md
docs/src/installation.md

This PR cleans up a few areas in the documentation with unclear wording

Clean up some wording in the documentation

---

docs/src/configure.md

Adds a few undocumented items to the configure documentation.
Closes #131

Add missing items to Dioxus.toml documentation

---

Cargo.lock
Cargo.toml
src/cli/cfg.rs
src/cli/create/mod.rs
src/cli/mod.rs
src/cli/translate/mod.rs
src/server/mod.rs

This makes a few improvements to dioxus create command:
- Make the command interactive
- Format the Dioxus.toml, Cargo.toml, and rust code after creating the application
- Link to cargo generate statically instead of assuming the user has installed cargo mdbook

Make Dioxus create interactive
