Cargo.toml
Not disabling default features brings in `termion` which causes a build failure
=> Fix build on windows

extension/LICENSE.txt, extension/package.json, extension/src/extension.ts
1. Refactored extension.ts, merge two functions to one, make it easy to maintain, and added hint to help beginner users
2. Renamed command name, make it unique to the vscode universe.
3. Added LIENSE.txt to prevent warning of vsce every time.
=> Refactor extension, make it easy to maintain and unique to register

src/server/mod.rs
It removes these bulid time warnings:
```
warning: use of deprecated struct `axum::AddExtensionLayer`: Use `axum::extract::Extension` instead. It implements `tower::Layer`
--> src/server/mod.rs:6:5
|
6 |     AddExtensionLayer, Router,
|     ^^^^^^^^^^^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
warning: use of deprecated struct `axum::AddExtensionLayer`: Use `axum::extract::Extension` instead. It implements `tower::Layer`
--> src/server/mod.rs:91:24
|
91 |                 .layer(AddExtensionLayer::new(ws_reload_state))
|                        ^^^^^^^^^^^^^^^^^
warning: `dioxus-cli` (lib) generated 2 warnings
Finished dev [unoptimized + debuginfo] target(s) in 0.09s
```
=> Remove axum warnings

src/cli/create/mod.rs
I got an unclear error during the creation process:
```
~/lab$ dioxus create hi-dioxus --template gh:dioxuslabs/dioxus-template
[INFO] 🔧 Start to create a new project 'hi-dioxus'.
Error: ⛔   Git Error: unexpected http status code: 400; class=Http (34)
[ERROR] create error: Generate project failed.
```
The cause happened to be an old version of `cargo-generate` (v0.11.1). After updating to the last release (v0.13.0) the error is gone, so I've added this hint.
=> A hint to update cargo-generate

src/cargo.rs, src/config.rs
With having cargo target folder globally redefined in `~/.cargo/config`, I had a error while running `dioxus serve`:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: failed to read `/data/0/lab/hi-dioxus/target/wasm32-unknown-unknown/debug/hi-dioxus.wasm`
Caused by:
0: failed to read `/data/0/lab/hi-dioxus/target/wasm32-unknown-unknown/debug/hi-dioxus.wasm`
1: No such file or directory (os error 2)', /home/imbolc/.cargo/registry/src/github.com-1ecc6299db9ec823/dioxus-cli-0.1.4/src/builder.rs:92:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ERROR] Bindgen build failed! 
This is probably due to the Bindgen version, dioxus-cli using `0.2.79` Bindgen crate.
[ERROR] serve error: I/O Error: No such file or directory (os error 2)
```
=> Fix buliding with redefined cargo target dir

Cargo.toml, src/config.rs, src/server/mod.rs
This was a bit challenging specifically due to the asset dir also being the root dir.  Otherwise one could simply `nest` into asset, then `fallback` to a `ServeFile`.
=> Service index.html on 404 (for SPA)

Cargo.toml, src/cli/cfg.rs, src/cli/serve/mod.rs, src/config.rs, src/hot_reload/mod.rs, src/lib.rs, src/server/hot_reload.rs, src/server/mod.rs
Adds a hot-reload flag that integrates with https://github.com/DioxusLabs/dioxus/pull/425. If only the rsx is changed is sends the new rsx with a websocket without needing to recompile.
Resolves https://github.com/DioxusLabs/dioxus/issues/408
Demo:
https://user-images.githubusercontent.com/66571940/174206798-1b73e42a-0b36-4bce-83c4-aa7d875ec800.mp4
=> Add Hot reload rsx to dioxus serve

src/server/hot_reload.rs, src/server/mod.rs
pending https://github.com/DioxusLabs/dioxus/pull/462
Changes the path separator to not depend on the build target.
=> fix path separator for hot reloading

src/cli/build/mod.rs, src/cli/clean/mod.rs, src/cli/create/mod.rs, src/cli/mod.rs, src/cli/tool/mod.rs, src/cli/translate/mod.rs, src/error.rs, src/main.rs
This helps, for example, catching errors returned by dioxus-cli when used in a CI script or other build process.
=> Return non-zero exit code on error

src/server/mod.rs
1. Add a fallback for `cls` and `clear` both not found.
2. Fix panic for some rich-featured editor like jetbrains' saving file to a temp file like `main.rs~` first then moved to original file.
=> Fix problems on windows and jetbrains

docs/src/configure.md
change "Application.Tool" to "Application.Tools" to avoid user from typing "[application.tool]" in Dioxus.toml
=> Update doc to avoid misunderstanding

src/cli/create/mod.rs, src/main.rs
closes #60
---
Notes:
1. While handing the default `DioxusConfig` in case of an err is done in main, an alternative is to introduce a `DioxusConfig::init()` function, so that `main()` remains pretty simple. I like this and I'd include this if you also agree.
1. The `--force` flag on `cargo generate` follows the `cargo-generate`'s flag based on which the project is not renamed.
Thus, there is no error after that, as this CLI expects the user provided name to remain the same.
=> fix(#60): handling default cfg & kebab_case name

src/assets/dioxus.toml
index_on_404 was never used with the default config because the property is set on `web.watcher` and not on `web.app`
=> Move property so it is in the right category

Cargo.lock, Cargo.toml, src/builder.rs
When I edit the source code when dioxus serve on Windows, it freezes with the following display.
```
[INFO] 🪁 Rebuild project
[INFO] 🚅 Running build command...
| 💼 Waiting to start build the project...        
```
This problem occurs when the source code is edited in IntelliJ IDEA and VSCode.
For some reason it does not happen when editing with notepad. (Probably because notepad does not run Cargo.)
The problem seems to be related to the handling of stdout, stderr of the subprocess.
I could not modify it to work with the standard library, so I used subprocess crate and it works.
=> fix: rebuild hangs on windows

Cargo.lock, Cargo.toml, docs/src/configure.md, src/config.rs, src/error.rs, src/server/mod.rs, src/server/proxy.rs
This adds an MVP of some proxying capabilities to the `dioxus serve`
server. The config is similar to that of `trunk serve`: the user can
specify one or more proxy backends under `[[web.proxy]]` in Dioxus.toml,
and the server will intercept requests targeted at the _path_ of that
configured backend and forward them to the backend server.
Example
-------
For example, if the dev server is serving on port 8080 with this config:
```
[[web.proxy]]
backend = "http://localhost:9000/api"
```
then requests to http://localhost:8080/api,
http://localhost:8080/api/ and http://localhost:8080/api/any-subpath
to be forwarded to the respective paths on http://localhost:9000.
This PR doesn't handle path rewriting or anything yet but it would be
fairly simple to add in future if anyone needs it.
=> Add minimal proxy capabilities to `dioxus serve`

Cargo.lock
Right now, `master` fails, if it's build with the dependencies specified in the Cargo.lock file.
Installing it only works, because `cargo install` doesn't use the `--locked` flag by default. `cargo build` however does and fails by default.
=> chore: Bump deps and fix failing compilation

src/cargo.rs
I was wondering what the previous error message ment. So I had to look it up.
Cargo directory might just mean ~/.cargo
=> Make error more illuminating

src/cli/build/mod.rs
Update the build config to read any provided --features flags.
Without this, it does not seem possible to combine SSR + Web platforms while also using dioxus-router.
----
Due to weak dependency on the "web" feature from dioxus-router crate - I need the ability to conditional turn on dioxus-router/web while building the Web platform.
=> Build with --features cli argument

Cargo.lock, Cargo.toml, docs/src/cmd/serve.md, src/cli/cfg.rs, src/cli/serve/mod.rs, src/server/mod.rs
This PR adds the "--open" CLI parameter to the "serve" option, allowing the CLI to open the app in the user's default browser.
`dioxus serve --open` will open the app in the default browser.
`dioxus serve --open --hot-reload` will do the same, but with hot-reloading active.
This is just a nice-to-have feature that Trunk has and that I kind of miss since switching to Dioxus CLI.
This may introduce a bug in certain systems where the browser starts too early and times out as the server hasn't finished starting, meaning the user will have to manually refresh once the server starts. 
A fix would involve starting the server, then probing the URL to see what response it returns before actually opening the browser (but that would require spawning a separate process/thread and adding too much …
=> feat: add "--open" option to `dioxus serve`

Cargo.lock, Cargo.toml, docs/src/cmd/serve.md, src/cli/cfg.rs, src/cli/serve/mod.rs, src/config.rs, src/server/mod.rs
Already tested.
If this option is not enabled, `serve` should behave exactly the same as current implementation.
```
~  dioxus serve --help                                
dioxus-serve 
Build, watch & serve the Rust WASM app and all of its assets
USAGE:
dioxus serve [OPTIONS] [TARGET]
ARGS:
<TARGET>    The index HTML file to drive the bundling process [default: index.html]
OPTIONS:
--example <EXAMPLE>      Build a example [default: ""]
--features <FEATURES>    Space separated list of features to activate
-h, --help                   Print help information
--hot-reload             Build with hot reloading rsx [default: false]
--platform <PLATFORM>    Build platform: support Web & Desktop [default: "default_platform"]
--port <PORT>            Port of dev server [default: 8080]
--profile …
```
=> add shared array buffer support for dev server as optional config

extension/src/main.ts, src/cli/autoformat/mod.rs
CLI was passing the String after the --file flag to the autofmt crate when it expected the file's contents.
Closes DioxusLabs/Dioxus#1042
=> Fix formatting a single file with --file flag

src/cli/serve/mod.rs
The dioxus serve tool does not host the assets on the right subdirectory when using base_path. I tried fixing the axum code, but I don't know how to move the fileserver into it's own subpath.
I think ignoring the base_path is a good workaround for now.
=> Ignore base_path changes for serve

src/config.rs
1. first binary alphabetically
2. library 
1. default-run binary
2. binary with name of crate or located at src/main.rs
3. first binary alphabetically
4. library
=> fix chosing launch target

src/builder.rs
Fixes https://github.com/DioxusLabs/cli/issues/146
This changes the CLI index.html processing to automatically add scripts and asset links when the template markers are not found
=> Automatically insert scripts if they are not found
